name: snazzle_common
description: Data structures and logic that are common between Snazzle client and server
# version: 1.0.0
# homepage: https://www.example.com
private: true

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
